from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from typing import Any

IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def property_name(value: str) -> str:
    return value if IDENTIFIER.fullmatch(value) else json.dumps(value, ensure_ascii=False)


def ts_type(schema: Any) -> str:
    if not isinstance(schema, dict):
        return "unknown"
    reference = schema.get("$ref")
    if isinstance(reference, str):
        return reference.rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    values = schema.get("enum")
    if isinstance(values, list):
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in values) or "never"
    for keyword, separator in (("oneOf", " | "), ("anyOf", " | "), ("allOf", " & ")):
        variants = schema.get(keyword)
        if isinstance(variants, list):
            return separator.join(f"({ts_type(item)})" for item in variants) or "unknown"

    raw_type = schema.get("type")
    if isinstance(raw_type, list):
        return " | ".join(ts_type({**schema, "type": item}) for item in raw_type)
    if raw_type == "null":
        return "null"
    if raw_type == "boolean":
        return "boolean"
    if raw_type in {"integer", "number"}:
        return "number"
    if raw_type == "string":
        return "string"
    if raw_type == "array":
        return f"Array<{ts_type(schema.get('items'))}>"
    if raw_type == "object" or "properties" in schema or "additionalProperties" in schema:
        properties = schema.get("properties")
        required = set(schema.get("required", []))
        members: list[str] = []
        if isinstance(properties, dict):
            for name, item in properties.items():
                optional = "" if name in required else "?"
                members.append(f"{property_name(name)}{optional}: {ts_type(item)}")
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            members.append(f"[key: string]: {ts_type(additional)}")
        elif additional is True:
            members.append("[key: string]: unknown")
        return "{ " + "; ".join(members) + " }"
    return "unknown"


def render(document: dict[str, Any]) -> str:
    schemas = document.get("components", {}).get("schemas", {})
    if not isinstance(schemas, dict):
        raise ValueError("OpenAPI components.schemas must be an object")
    canonical = json.dumps(document, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()
    digest = hashlib.sha256(canonical).hexdigest()
    lines = [
        "/* This file is generated by scripts/generate_typescript_sdk.py. */",
        f'export const OPENAPI_SHA256 = "{digest}" /** gitleaks:allow - public contract digest */;',
        "",
        "export namespace OpenApi {",
    ]
    for name, schema in sorted(schemas.items()):
        if not IDENTIFIER.fullmatch(name):
            raise ValueError(f"OpenAPI schema name is not a TypeScript identifier: {name}")
        lines.append(f"  export type {name} = {ts_type(schema)};")
    lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate TypeScript schema types from Scenara OpenAPI")
    parser.add_argument("--openapi", type=Path, default=Path("docs/openapi.json"))
    parser.add_argument("--output", type=Path, default=Path("sdk/typescript/src/generated.ts"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    document = json.loads(args.openapi.read_text(encoding="utf-8"))
    expected = render(document)
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != expected:
            raise SystemExit("TypeScript SDK schema drifted; run scripts/generate_typescript_sdk.py")
        return
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8")


if __name__ == "__main__":
    main()
