apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scenara
resources:
  - namespace.yaml
  - configmap.yaml
  - api.yaml
  - workers.yaml
  - scheduler.yaml
  - autoscaling.yaml
  - networkpolicy.yaml
images:
  - name: scenara-api
    newTag: 0.3.0-dev.43
